name: Publish Master

on:
#  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
        env:
          TOKEN: ${{ secrets.AUTO_TOKEN }}
          USERNAME: ${{ secrets.AUTO_USERNAME }}
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          TOKEN: ${{ secrets.AUTO_TOKEN }}
          USERNAME: ${{ secrets.AUTO_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
      - name: Setup NPM
        run: npm config set //registry.npmjs.org/:_authToken=$token
        env:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Publish npm
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishToNpm
