name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Read version
        id: read_version
        uses: reedyuk/read-properties@v0.0.4
        with:
          path: 'gradle.properties'
          property: 'version'
      - name: Read version old
        id: read_version_old
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'version'
      - name: Update version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'version'
          value: "${{ steps.read_version.outputs.value }}-${{ github.run_id }}"

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jvmTest
      - name: Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          report_paths: "build/test-results/jvmTest/*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository
        env:
          TOKEN: ${{ secrets.AUTO_TOKEN }}
          USERNAME: ${{ secrets.AUTO_USERNAME }}
      - name: Setup NPM
        run: npm config set //npm.pkg.github.com/:_authToken=$token
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish npm
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishToNpm
